version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: eduracer
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JDBC_DATABASE_URL=jdbc:mysql://mysql:3306/eduracer
      - JDBC_DATABASE_USERNAME=root
      - JDBC_DATABASE_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - JWT_SECRET=${JWT_SECRET:-your-prod-secret-key}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-https://eduracer-game.windsurf.build}
    depends_on:
      - mysql

volumes:
  mysql_data:
